INSERT ALL
    INTO department(department_id, department_name) VALUES (10, 'Administration')
    INTO department(department_id, department_name) VALUES (20, 'Marketing')
    INTO department(department_id, department_name) VALUES (30, 'Purchasing')
    INTO department(department_id, department_name) VALUES (40, 'Human Resources')
    INTO department(department_id, department_name) VALUES (50, 'Shipping')
    INTO department(department_id, department_name) VALUES (60, 'IT')
    INTO department(department_id, department_name) VALUES (70, 'Public Relations')
    INTO department(department_id, department_name) VALUES (80, 'Sales')
    INTO department(department_id, department_name) VALUES (90, 'Executive')
    INTO department(department_id, department_name) VALUES (100, 'Finance')
    INTO department(department_id, department_name) VALUES (110, 'Accounting')
    INTO department(department_id, department_name) VALUES (120, 'Treasury')
    INTO department(department_id, department_name) VALUES (130, 'Corporate Tax')
    INTO department(department_id, department_name) VALUES (140, 'Control And Credit')
    INTO department(department_id, department_name) VALUES (150, 'Shareholder Services')
    INTO department(department_id, department_name) VALUES (160, 'Benefits')
    INTO department(department_id, department_name) VALUES (170, 'Manufacturing')
    INTO department(department_id, department_name) VALUES (180, 'Construction')
    INTO department(department_id, department_name) VALUES (190, 'Contracting')
    INTO department(department_id, department_name) VALUES (200, 'Operations')
SELECT * FROM dual;