INSERT ALL
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1000, 'Av. Paulista, 1500', '01310-100',	'São Paulo', 'SP', 'Brazil')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1010, 'Rua da Consolação, 300', '01301-000',	'São Paulo', 'SP', 'Brazil')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1020, 'Av. Rio Branco, 100', '20040-002',	'Rio de Janeiro', 'RJ', 'Brazil')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1030, 'Av. Atlântica, 200', '22010-000',	'Rio de Janeiro', 'RJ', 'Brazil')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1040, 'Av. Afonso Pena, 1000', '30130-003',	'Belo Horizonte', 'MG', 'Brazil')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1050, 'Rua XV de Novembro, 500', '80020-310',	'Curitiba', 'PR', 'Brazil')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1060, 'Av. Ipiranga, 6681', '90619-900',	'Porto Alegre', 'RS', 'Brazil')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1070, 'Rua do Sol, 45', '40015-000',	'Salvador', 'BA', 'Brazil')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1080, 'Av. Boa Viagem, 3200', '51020-000',	'Recife', 'PE', 'Brazil')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1090, 'Av. Dom Pedro I, 2000', '60060-100',	'Fortaleza', 'CE', 'Brazil')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1100, '5th Avenue, 350', '10118', 'New York', 'NY', 'USA')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1110, 'Market Street, 700', '94103', 'San Francisco', 'CA', 'USA')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1120, 'Michigan Avenue, 200', '60601', 'Chicago', 'IL', 'USA')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1130, 'Oxford Street, 120', 'W1D 1LT', 'London', 'England', 'United Kingdom')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1140, 'Baker Street, 221', 'NW1 6XE', 'London', 'England', 'United Kingdom')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1150, 'Rue de Rivoli, 60', '75004', 'Paris', 'Île-de-France', 'France')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1160, 'Friedrichstraße, 88', '10117', 'Berlin', 'Berlin', 'Germany')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1170, 'Via del Corso, 45', '00186', 'Rome', 'Lazio', 'Italy')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1180, 'Paseo de la Castellana, 100', '28046', 'Madrid', 'Madrid', 'Spain')
    INTO location (location_id, street_address, postal_code, city, state_province, country) VALUES (1190, 'Toorak Road, 500', '3142', 'Melbourne', 'Victoria', 'Australia')
SELECT * FROM dual;