INSERT ALL 
    INTO benefit (benefit_id, benefit_name) VALUES (1, 'Health Insurance')
    INTO benefit (benefit_id, benefit_name) VALUES (2, 'Dental Insurance')
    INTO benefit (benefit_id, benefit_name) VALUES (3, 'Vision Insurance')
    INTO benefit (benefit_id, benefit_name) VALUES (4, 'Life Insurance')
    INTO benefit (benefit_id, benefit_name) VALUES (5, 'Disability Insurance')
    INTO benefit (benefit_id, benefit_name) VALUES (6, '401k Matching')
    INTO benefit (benefit_id, benefit_name) VALUES (7, 'Paid Time Off')
    INTO benefit (benefit_id, benefit_name) VALUES (8, 'Parental Leave')
    INTO benefit (benefit_id, benefit_name) VALUES (9, 'Gym Membership')
    INTO benefit (benefit_id, benefit_name) VALUES (10, 'Meal Voucher')
    INTO benefit (benefit_id, benefit_name) VALUES (11, 'Transportation Voucher')
    INTO benefit (benefit_id, benefit_name) VALUES (12, 'Education Assistance')
    INTO benefit (benefit_id, benefit_name) VALUES (13, 'Remote Work Allowance')
    INTO benefit (benefit_id, benefit_name) VALUES (14, 'Stock Options')
    INTO benefit (benefit_id, benefit_name) VALUES (15, 'Wellness Program')
    INTO benefit (benefit_id, benefit_name) VALUES (16, 'Childcare Assistance')
    INTO benefit (benefit_id, benefit_name) VALUES (17, 'Legal Assistance')
    INTO benefit (benefit_id, benefit_name) VALUES (18, 'Pet Insurance')
    INTO benefit (benefit_id, benefit_name) VALUES (19, 'Relocation Assistance')
    INTO benefit (benefit_id, benefit_name) VALUES (20, 'Annual Bonus')
SELECT * FROM dual;