INSERT ALL 
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (1, 1)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (1, 8)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (2, 1)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (3, 1)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (4, 2)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (5, 3)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (6, 3)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (6, 4)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (7, 1)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (8, 4)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (8, 14)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (9, 2)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (10, 1)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (11, 1)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (12, 3)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (13, 5)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (13, 6)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (14, 17)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (15, 2)
    INTO benefit_eligibility (benefit_id, eligibility_id) VALUES (16, 14)
SELECT * FROM dual;