INSERT ALL
    INTO employee_benefits (employee_id, benefit_id) VALUES (1, 20)
    INTO employee_benefits (employee_id, benefit_id) VALUES (1, 14)
    INTO employee_benefits (employee_id, benefit_id) VALUES (2, 6)
    INTO employee_benefits (employee_id, benefit_id) VALUES (3, 1)
    INTO employee_benefits (employee_id, benefit_id) VALUES (4, 6)
    INTO employee_benefits (employee_id, benefit_id) VALUES (5, 7)
    INTO employee_benefits (employee_id, benefit_id) VALUES (6, 9)
    INTO employee_benefits (employee_id, benefit_id) VALUES (7, 1)
    INTO employee_benefits (employee_id, benefit_id) VALUES (8, 13)
    INTO employee_benefits (employee_id, benefit_id) VALUES (9, 14)
    INTO employee_benefits (employee_id, benefit_id) VALUES (10, 1)
    INTO employee_benefits (employee_id, benefit_id) VALUES (11, 2)
    INTO employee_benefits (employee_id, benefit_id) VALUES (12, 10)
    INTO employee_benefits (employee_id, benefit_id) VALUES (13, 3)
    INTO employee_benefits (employee_id, benefit_id) VALUES (14, 12)
    INTO employee_benefits (employee_id, benefit_id) VALUES (15, 7)
    INTO employee_benefits (employee_id, benefit_id) VALUES (16, 11)
    INTO employee_benefits (employee_id, benefit_id) VALUES (17, 4)
    INTO employee_benefits (employee_id, benefit_id) VALUES (18, 20)
    INTO employee_benefits (employee_id, benefit_id) VALUES (19, 9)
    INTO employee_benefits (employee_id, benefit_id) VALUES (20, 6)
SELECT * FROM dual;

