INSERT ALL
    INTO request (request_id, employee_id, benefit_id) VALUES (1, 1, 20)
    INTO request (request_id, employee_id, benefit_id) VALUES (2, 2, 6)
    INTO request (request_id, employee_id, benefit_id) VALUES (3, 3, 1)
    INTO request (request_id, employee_id, benefit_id) VALUES (4, 4, 6)
    INTO request (request_id, employee_id, benefit_id) VALUES (5, 5, 7)
    INTO request (request_id, employee_id, benefit_id) VALUES (6, 6, 9)
    INTO request (request_id, employee_id, benefit_id) VALUES (7, 7, 1)
    INTO request (request_id, employee_id, benefit_id) VALUES (8, 8, 13)
    INTO request (request_id, employee_id, benefit_id) VALUES (9, 9, 14)
    INTO request (request_id, employee_id, benefit_id) VALUES (10, 10, 1)
    INTO request (request_id, employee_id, benefit_id) VALUES (11, 11, 2)
    INTO request (request_id, employee_id, benefit_id) VALUES (12, 12, 10)
    INTO request (request_id, employee_id, benefit_id) VALUES (13, 13, 3)
    INTO request (request_id, employee_id, benefit_id) VALUES (14, 14, 12)
    INTO request (request_id, employee_id, benefit_id) VALUES (15, 15, 7)
    INTO request (request_id, employee_id, benefit_id) VALUES (16, 16, 11)
    INTO request (request_id, employee_id, benefit_id) VALUES (17, 17, 4)
    INTO request (request_id, employee_id, benefit_id) VALUES (18, 18, 20)
    INTO request (request_id, employee_id, benefit_id) VALUES (19, 19, 9)
    INTO request (request_id, employee_id, benefit_id) VALUES (20, 20, 6)
SELECT * FROM dual;