INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(3, 1, TO_DATE('2023-01-01', 'YYYY-MM-DD'), 500.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(4, 2, TO_DATE('2023-01-01', 'YYYY-MM-DD'), 900.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(5, 1, TO_DATE('2024-05-10', 'YYYY-MM-DD'), 500.00, 'PENDING');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(3, 23, TO_DATE('2023-04-01', 'YYYY-MM-DD'), 1000.00, 'PENDING');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(4, 24, TO_DATE('2023-05-10', 'YYYY-MM-DD'), 150.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(5, 25, TO_DATE('2023-06-25', 'YYYY-MM-DD'), 100.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(3, 26, TO_DATE('2023-07-05', 'YYYY-MM-DD'), 250.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(4, 27, TO_DATE('2023-08-12', 'YYYY-MM-DD'), 150.00, 'PENDING');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(5, 28, TO_DATE('2023-09-01', 'YYYY-MM-DD'), 500.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(3, 1, TO_DATE('2023-09-15', 'YYYY-MM-DD'), 500.00, 'REVOKED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(4, 2, TO_DATE('2023-10-10', 'YYYY-MM-DD'), 900.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(5, 21, TO_DATE('2023-11-20', 'YYYY-MM-DD'), 300.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(3, 23, TO_DATE('2023-12-01', 'YYYY-MM-DD'), 1000.00, 'PENDING');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(4, 24, TO_DATE('2024-01-10', 'YYYY-MM-DD'), 150.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(5, 25, TO_DATE('2024-02-14', 'YYYY-MM-DD'), 100.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(3, 26, TO_DATE('2024-03-05', 'YYYY-MM-DD'), 250.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(4, 27, TO_DATE('2024-04-12', 'YYYY-MM-DD'), 150.00, 'PENDING');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(5, 28, TO_DATE('2024-05-01', 'YYYY-MM-DD'), 500.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(3, 1, TO_DATE('2024-06-15', 'YYYY-MM-DD'), 500.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(4, 2, TO_DATE('2024-07-10', 'YYYY-MM-DD'), 900.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(49, 25, TO_DATE('2023-02-11', 'YYYY-MM-DD'), 614.25, 'PENDING');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(36, 1, TO_DATE('2023-04-23', 'YYYY-MM-DD'), 487.83, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(5, 2, TO_DATE('2023-11-01', 'YYYY-MM-DD'), 900.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(41, 22, TO_DATE('2023-08-29', 'YYYY-MM-DD'), 200.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(42, 24, TO_DATE('2023-07-10', 'YYYY-MM-DD'), 150.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(43, 26, TO_DATE('2023-05-19', 'YYYY-MM-DD'), 250.00, 'PENDING');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(44, 28, TO_DATE('2023-03-07', 'YYYY-MM-DD'), 500.00, 'GRANTED');
INSERT INTO employees_benefits(employee_id, benefit_id, concession_date, granted_value, status) VALUES(45, 27, TO_DATE('2023-06-11', 'YYYY-MM-DD'), 150.00, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (23, 22, TO_DATE('2024-05-01', 'YYYY-MM-DD'), 200, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (24, 23, TO_DATE('2024-05-03', 'YYYY-MM-DD'), 1000, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (25, 24, TO_DATE('2024-06-15', 'YYYY-MM-DD'), 150, 'PENDING');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (26, 25, TO_DATE('2024-07-01', 'YYYY-MM-DD'), 100, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (27, 26, TO_DATE('2024-05-21', 'YYYY-MM-DD'), 250, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (28, 27, TO_DATE('2024-06-05', 'YYYY-MM-DD'), 150, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (29, 28, TO_DATE('2024-07-10', 'YYYY-MM-DD'), 500, 'PENDING');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (30, 2, TO_DATE('2024-08-01', 'YYYY-MM-DD'), 900, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (31, 21, TO_DATE('2024-06-30', 'YYYY-MM-DD'), 300, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (32, 22, TO_DATE('2024-06-25', 'YYYY-MM-DD'), 200, 'PENDING');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (33, 23, TO_DATE('2024-05-30', 'YYYY-MM-DD'), 1000, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (34, 24, TO_DATE('2024-05-05', 'YYYY-MM-DD'), 150, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (35, 25, TO_DATE('2024-07-20', 'YYYY-MM-DD'), 100, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (37, 26, TO_DATE('2024-07-05', 'YYYY-MM-DD'), 250, 'PENDING');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (38, 27, TO_DATE('2024-06-18', 'YYYY-MM-DD'), 150, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (39, 28, TO_DATE('2024-07-03', 'YYYY-MM-DD'), 500, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (40, 1, TO_DATE('2024-07-11', 'YYYY-MM-DD'), 500, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (46, 21, TO_DATE('2024-07-09', 'YYYY-MM-DD'), 300, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (47, 22, TO_DATE('2024-08-01', 'YYYY-MM-DD'), 200, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (48, 23, TO_DATE('2024-07-15', 'YYYY-MM-DD'), 1000, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (50, 24, TO_DATE('2024-06-16', 'YYYY-MM-DD'), 150, 'PENDING');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (51, 25, TO_DATE('2024-06-21', 'YYYY-MM-DD'), 100, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (52, 26, TO_DATE('2024-05-11', 'YYYY-MM-DD'), 250, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (53, 27, TO_DATE('2024-06-06', 'YYYY-MM-DD'), 150, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (54, 28, TO_DATE('2024-05-22', 'YYYY-MM-DD'), 500, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (55, 1, TO_DATE('2024-08-01', 'YYYY-MM-DD'), 500, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (56, 2, TO_DATE('2024-08-02', 'YYYY-MM-DD'), 900, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (57, 21, TO_DATE('2024-08-03', 'YYYY-MM-DD'), 300, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (58, 22, TO_DATE('2024-06-19', 'YYYY-MM-DD'), 200, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (59, 23, TO_DATE('2024-06-27', 'YYYY-MM-DD'), 1000, 'PENDING');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (60, 24, TO_DATE('2024-05-17', 'YYYY-MM-DD'), 150, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (61, 25, TO_DATE('2024-06-13', 'YYYY-MM-DD'), 100, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (62, 26, TO_DATE('2024-07-04', 'YYYY-MM-DD'), 250, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (63, 27, TO_DATE('2024-07-20', 'YYYY-MM-DD'), 150, 'PENDING');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (64, 28, TO_DATE('2024-07-01', 'YYYY-MM-DD'), 500, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (65, 1, TO_DATE('2024-07-22', 'YYYY-MM-DD'), 500, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (66, 2, TO_DATE('2024-08-04', 'YYYY-MM-DD'), 900, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (67, 21, TO_DATE('2024-08-02', 'YYYY-MM-DD'), 300, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (23, 1, TO_DATE('2024-05-12', 'YYYY-MM-DD'), 500, 'PENDING');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (24, 2, TO_DATE('2024-06-01', 'YYYY-MM-DD'), 900, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (25, 21, TO_DATE('2024-06-07', 'YYYY-MM-DD'), 300, 'GRANTED');
INSERT INTO employees_benefits (employee_id, benefit_id, concession_date, granted_value, status) VALUES (26, 22, TO_DATE('2024-06-15', 'YYYY-MM-DD'), 200, 'GRANTED');