CREATE TABLE positions(
    id_position NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR2(50) NOT NULL,
    position_level VARCHAR2(20),

    CONSTRAINT pk_position PRIMARY KEY(id_position),
    CONSTRAINT uq_positions_name UNIQUE(name)
);

CREATE TABLE employees(
    id_employee NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name VARCHAR2(100) NOT NULL,
    hire_date DATE NOT NULL,
    position_id NUMBER NOT NULL,

    CONSTRAINT pk_employee PRIMARY KEY(id_employee),
    CONSTRAINT fk_employees_positions FOREIGN KEY(position_id) REFERENCES positions(id_position)
);

CREATE TABLE benefits(
    id_benefit NUMBER GENERATED BY DEFAULT AS  IDENTITY NOT NULL,
    name VARCHAR2(50) NOT NULL,
    type VARCHAR2(30) NOT NULL,
    base_value NUMBER(10,2),
    validity_months NUMBER,
    
    CONSTRAINT pk_benefit PRIMARY KEY(id_benefit),
    CONSTRAINT uq_benefits_name UNIQUE(name)
);

CREATE TABLE concession_criteria(
    id_criteria NUMBER GENERATED BY DEFAULT AS  IDENTITY NOT NULL,
    benefit_id NUMBER NOT NULL,
    criteria_type VARCHAR2(30) NOT NULL,
    reference_value VARCHAR2(100) NOT NULL,

    CONSTRAINT pk_criteria PRIMARY KEY(id_criteria),
    CONSTRAINT fk_concession_criteria_benefits FOREIGN KEY(benefit_id) REFERENCES benefits(id_benefit)
);

CREATE TABLE employees_benefits(
    employee_id NUMBER NOT NULL,
    benefit_id NUMBER NOT NULL,
    concession_date DATE NOT NULL,
    granted_value NUMBER(10,2) NOT NULL,
    status VARCHAR2(20) NOT NULL,

    CONSTRAINT pk_employees_benefits PRIMARY KEY(employee_id, benefit_id, concession_date),
    CONSTRAINT fk_employees_benefits_employees FOREIGN KEY(employee_id) REFERENCES employees(id_employee),
    CONSTRAINT fk_employees_benefits_benefits FOREIGN KEY(benefit_id) REFERENCES benefits(id_benefit)
);